/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fyp.midtermproject;

import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Altaf Hussain
 */
public class ADVISORYsecJFrame extends javax.swing.JFrame {
     FilehandlingFYP f = new FilehandlingFYP();
          DefaultTableModel model;

    /**
     * Creates new form ADVISORYsecJFrame
     */
    public ADVISORYsecJFrame() {
        initComponents();
         this.model = new DefaultTableModel();
        model.addColumn("1st StudentName");
        model.addColumn("2nd StudentName");
        model.addColumn("1st StudentID");
        model.addColumn("2nd StudentID");
        model.addColumn("Project");
        model.addColumn("Each_Evaluation");
        model.addColumn("Total_Evaluation");
        TableSheet.setModel(model);
    }
    
    public ArrayList ListSTDmarksheet(String STD_Name1, String STD_Name2, String STD_ID1, String STD_ID2, String Project, String Each_evl, String Total_evl)
    {
        ArrayList<AdvisorySecData> list = new ArrayList<>() ;
        AdvisorySecData ASd = new AdvisorySecData( STD_Name1, STD_Name2, STD_ID1, STD_ID2, Project, Each_evl, Total_evl);
        list.add(ASd);
       
        return list;
      }
  
     public void addRow(String STD_Name1, String STD_Name2, String STD_ID1, String STD_ID2, String Project, String Each_evl, String Total_evl)
    {
        DefaultTableModel model = (DefaultTableModel) TableSheet.getModel();
         ArrayList<AdvisorySecData> list = ListSTDmarksheet( STD_Name1, STD_Name2, STD_ID1, STD_ID2, Project, Each_evl, Total_evl);
         Object rowData[] = new Object[7];
         for (int i =0 ;i < list.size(); i++)
         {
             rowData[0] = list.get(i).STD_Name1;
             rowData[1] = list.get(i).STD_Name2;
             rowData[2] = list.get(i).STD_ID1;
             rowData[3] = list.get(i).STD_ID2;
             rowData[4] = list.get(i).Project;
             rowData[5] = list.get(i).Each_evl;
             rowData[6] = list.get(i).Total_evl;
             model.addRow(rowData);
         }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameS1 = new javax.swing.JTextField();
        nameS2 = new javax.swing.JTextField();
        IDs1 = new javax.swing.JTextField();
        Projectname = new javax.swing.JTextField();
        IDs2 = new javax.swing.JTextField();
        singleEVL = new javax.swing.JTextField();
        totalEVL = new javax.swing.JTextField();
        CancelBTN = new javax.swing.JButton();
        AddBTN = new javax.swing.JButton();
        UpdBTN = new javax.swing.JButton();
        DeleteBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSheet = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();
        SaveData = new javax.swing.JButton();
        CancelBTN1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Advisory Board (Evaluation Checking)");

        jLabel2.setText("Name of 1st student");

        jLabel3.setText("Name of 2nd student");

        jLabel4.setText("ID of 1st student");

        jLabel5.setText("ID of 2nd student");

        jLabel6.setText("Marks of Each evaluation");

        jLabel7.setText("Project");

        jLabel8.setText("Marks of Total evaluation");

        nameS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameS2ActionPerformed(evt);
            }
        });

        Projectname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectnameActionPerformed(evt);
            }
        });

        singleEVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleEVLActionPerformed(evt);
            }
        });

        CancelBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelBTN.setText("Export");
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });

        AddBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddBTN.setText("Add");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        UpdBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UpdBTN.setText("Update");
        UpdBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdBTNActionPerformed(evt);
            }
        });

        DeleteBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DeleteBTN.setText("Delete");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        TableSheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableSheet);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        SearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchFieldKeyReleased(evt);
            }
        });

        SaveData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaveData.setText("SaveData");
        SaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDataActionPerformed(evt);
            }
        });

        CancelBTN1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelBTN1.setText("Exit");
        CancelBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SaveData)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBTN)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBTN1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel6))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameS1)
                            .addComponent(nameS2)
                            .addComponent(IDs1)
                            .addComponent(IDs2)
                            .addComponent(Projectname)
                            .addComponent(singleEVL)
                            .addComponent(totalEVL, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdBTN)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(43, 43, 43)
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(IDs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(IDs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Projectname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(singleEVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(totalEVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBTN)
                            .addComponent(UpdBTN)
                            .addComponent(DeleteBTN))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameS2ActionPerformed

    private void ProjectnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProjectnameActionPerformed

    private void singleEVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleEVLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singleEVLActionPerformed

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        // TODO add your handling code here:
        f.saveEvlMarksData("Marksheet.csv");
        this.dispose();
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void SaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDataActionPerformed
        // TODO add your handling code here:
        JFileChooser  chooser = new JFileChooser(); 
   
    chooser.setDialogTitle("Choose a destination to save exported file");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    //
    // disable the "All files" option.
    //
    //chooser.setAcceptAllFileFilterUsed(false);
    
    if(chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) { 
     f.saveEvlMarksData(chooser.getSelectedFile()+".csv");
      
      }
    else {
      System.out.println("No Selection ");
      }
    }//GEN-LAST:event_SaveDataActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        // TODO add your handling code here:
           String STD_Name1 = nameS1.getText();
           String STD_Name2 = nameS2.getText();
           String STD_ID1 = IDs1.getText();
           String STD_ID2 = IDs2.getText();
           String Project = Projectname.getText();
           String Each_evl = singleEVL.getText() ;
           String Total_evl = totalEVL.getText();
                 
             addRow( STD_Name1, STD_Name2, STD_ID1, STD_ID2, Project, Each_evl, Total_evl);
             nameS1.setText("");
             nameS2.setText("");
             IDs1.setText("");
             IDs2.setText("");
             Projectname.setText("");
             singleEVL.setText("") ;
             totalEVL.setText("");
    }//GEN-LAST:event_AddBTNActionPerformed

    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model= (DefaultTableModel) TableSheet.getModel();
        if(TableSheet.getSelectedRowCount()==1)
        {
            model.removeRow(TableSheet.getSelectedRow());
        }
        else
        {
            if(TableSheet.getRowCount()==0)
            {
            JOptionPane.showMessageDialog(null,"Table is empty");
        }
        else{
           JOptionPane.showMessageDialog(null,"Please select any row!");
        }
        }
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void UpdBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdBTNActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
         DefaultTableModel model= (DefaultTableModel) TableSheet.getModel();
        if(TableSheet.getSelectedRowCount()==1){
            String STD_Name1 = nameS1.getText();
           String STD_Name2 = nameS2.getText();
           String STD_ID1 = IDs1.getText();
           String STD_ID2 = IDs2.getText();
           String Project = Projectname.getText();
           String Each_evl = singleEVL.getText() ;
           String Total_evl = totalEVL.getText();
           
        TableSheet.setValueAt(STD_Name1 , TableSheet.getSelectedRow(), 0);
        TableSheet.setValueAt(STD_Name2, TableSheet.getSelectedRow(), 1);
        TableSheet.setValueAt(STD_ID1, TableSheet.getSelectedRow(), 2);
        TableSheet.setValueAt(STD_ID2, TableSheet.getSelectedRow(), 3);
        TableSheet.setValueAt(Project, TableSheet.getSelectedRow(), 4);
        TableSheet.setValueAt(Each_evl, TableSheet.getSelectedRow(), 5);
        TableSheet.setValueAt(Total_evl, TableSheet.getSelectedRow(), 6);
        
        JOptionPane.showMessageDialog(null," Updated Successfully!");
        }
        else{
        if(TableSheet.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Your Table is empty");
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select any row to update!");
        }
        }
    }//GEN-LAST:event_UpdBTNActionPerformed

    private void SearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFieldKeyReleased
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) TableSheet.getModel();
        String search = SearchField.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        TableSheet.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_SearchFieldKeyReleased

    private void CancelBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTN1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADVISORYsecJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADVISORYsecJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADVISORYsecJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADVISORYsecJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADVISORYsecJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JButton CancelBTN1;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JTextField IDs1;
    private javax.swing.JTextField IDs2;
    private javax.swing.JTextField Projectname;
    private javax.swing.JButton SaveData;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTable TableSheet;
    private javax.swing.JButton UpdBTN;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameS1;
    private javax.swing.JTextField nameS2;
    private javax.swing.JTextField singleEVL;
    private javax.swing.JTextField totalEVL;
    // End of variables declaration//GEN-END:variables
}
