/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fyp.midtermproject;

import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Altaf Hussain
 */
public class STdsecJFrame extends javax.swing.JFrame {
    FilehandlingFYP f = new FilehandlingFYP();
    DefaultTableModel model;

    /**
     * Creates new form STdsecJFrame
     */
    public STdsecJFrame() {
        initComponents();
          this.model = new DefaultTableModel();
        model.addColumn("1st StudentName");
        model.addColumn("2nd StudentName");
        model.addColumn("1st StudentID");
        model.addColumn("2nd StudentID");
        model.addColumn("1st StudentSession");
        model.addColumn("2nd StudentSession");
        model.addColumn("Project");
        Tableselec.setModel(model);
    }
    
    public ArrayList ListSTDSelection(String Name1,String Name2,String ID1,String ID2,String Session1,String Session2,String Project)
    {
        ArrayList<STDSelecData> list = new ArrayList<>() ;
        STDSelecData SSd = new STDSelecData( Name1, Name2, ID1, ID2, Session1, Session2, Project);
        list.add(SSd);
       
        return list;
      }
  
     public void addRow(String Name1,String Name2,String ID1,String ID2,String Session1,String Session2,String Project)
    {
        DefaultTableModel model = (DefaultTableModel) Tableselec.getModel();
         ArrayList<STDSelecData> list = ListSTDSelection( Name1, Name2, ID1, ID2, Session1, Session2, Project);
         Object rowData[] = new Object[7];
         for (int i =0 ;i < list.size(); i++)
         {
             rowData[0] = list.get(i).Name1;
             rowData[1] = list.get(i).Name2;
             rowData[2] = list.get(i).ID1;
             rowData[3] = list.get(i).ID2;
             rowData[4] = list.get(i).Session1;
             rowData[5] = list.get(i).Session2;
             rowData[6] = list.get(i).Project;
             model.addRow(rowData);
         }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AddBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        ExportBTN = new javax.swing.JButton();
        name_S1 = new javax.swing.JTextField();
        name_S2 = new javax.swing.JTextField();
        Id_S1 = new javax.swing.JTextField();
        Id_S2 = new javax.swing.JTextField();
        session_S1 = new javax.swing.JTextField();
        session_S2 = new javax.swing.JTextField();
        Prj = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tableselec = new javax.swing.JTable();
        CancelBtTN = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        CancelBtTN1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Student Selection Form");

        jLabel2.setText("Name of 1st student");

        jLabel3.setText("Name of 2nd student ");

        jLabel4.setText("ID of 1st student");

        jLabel5.setText("ID of 2nd Student");

        jLabel6.setText("Session of 1st student");

        jLabel7.setText("Session of 2nd Student");

        jLabel8.setText("Project Title");

        AddBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddBTN.setText("Add");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        UpdateBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UpdateBTN.setText("Update");
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        ExportBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExportBTN.setText("SaveData");
        ExportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportBTNActionPerformed(evt);
            }
        });

        name_S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_S2ActionPerformed(evt);
            }
        });

        Id_S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_S2ActionPerformed(evt);
            }
        });

        session_S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                session_S1ActionPerformed(evt);
            }
        });

        Tableselec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Tableselec);

        CancelBtTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelBtTN.setText("Export");
        CancelBtTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtTNActionPerformed(evt);
            }
        });

        SearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchFieldKeyReleased(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        CancelBtTN1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelBtTN1.setText("Exit");
        CancelBtTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Prj, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(session_S2)
                            .addComponent(session_S1)
                            .addComponent(Id_S2)
                            .addComponent(Id_S1)
                            .addComponent(name_S2)
                            .addComponent(name_S1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ExportBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelBtTN)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBtTN1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(522, 522, 522)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_S1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name_S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Id_S1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Id_S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(session_S1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(session_S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Prj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelBtTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExportBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelBtTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateBTN)
                            .addComponent(AddBTN))
                        .addGap(33, 33, 33))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_S2ActionPerformed

    private void Id_S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_S2ActionPerformed

    private void session_S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_session_S1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_session_S1ActionPerformed

    private void ExportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportBTNActionPerformed
        // TODO add your handling code here:
       JFileChooser  chooser = new JFileChooser(); 
   
    chooser.setDialogTitle("Choose a destination to save exported file");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    //
    // disable the "All files" option.
    //
    //chooser.setAcceptAllFileFilterUsed(false);
    
    if(chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) { 
     f.saveSTDselectionData(chooser.getSelectedFile()+".csv");
      
      }
    else {
      System.out.println("No Selection ");
      }
    }//GEN-LAST:event_ExportBTNActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        // TODO add your handling code here:
            String Name1 = name_S1.getText();
            String Name2 = name_S2.getText();
            String ID1 = Id_S1.getText();
            String ID2 = Id_S2.getText();
            String Session1 = session_S1.getText();
            String Session2 = session_S2.getText();
            String Project = Prj.getText();
                 
             addRow( Name1, Name2, ID1, ID2, Session1, Session2, Project);
             name_S1.setText("");
             name_S2.setText("");
             Id_S1.setText("");
             Id_S2.setText("");
             session_S1.setText("");
             session_S2.setText("");
             Prj.setText("");
    }//GEN-LAST:event_AddBTNActionPerformed

    private void CancelBtTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtTNActionPerformed
        // TODO add your handling code here:
        f.saveSTDselectionData("STDSelection.csv");
        this.dispose();
    }//GEN-LAST:event_CancelBtTNActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model= (DefaultTableModel) Tableselec.getModel();
        if(Tableselec.getSelectedRowCount()==1){
            String Name1 = name_S1.getText();
            String Name2 = name_S2.getText();
            String ID1 = Id_S1.getText();
            String ID2 = Id_S2.getText();
            String Session1 = session_S1.getText();
            String Session2 = session_S2.getText();
            String Project = Prj.getText();
                 
        Tableselec.setValueAt(Name1 , Tableselec.getSelectedRow(), 0);
        Tableselec.setValueAt(Name2, Tableselec.getSelectedRow(), 1);
        Tableselec.setValueAt(ID1, Tableselec.getSelectedRow(), 2);
        Tableselec.setValueAt(ID2, Tableselec.getSelectedRow(), 3);
        Tableselec.setValueAt(Session1, Tableselec.getSelectedRow(), 4);
        Tableselec.setValueAt(Session2, Tableselec.getSelectedRow(), 5);
        Tableselec.setValueAt(Project, Tableselec.getSelectedRow(), 6);
        
        JOptionPane.showMessageDialog(null," Updated Successfully!");
        }
        else{
        if(Tableselec.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Your Table is empty");
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select any row to update!");
        }
        }
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void SearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFieldKeyReleased
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) Tableselec.getModel();
        String search = SearchField.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        Tableselec.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_SearchFieldKeyReleased

    private void CancelBtTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtTN1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelBtTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STdsecJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STdsecJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STdsecJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STdsecJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STdsecJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JButton CancelBtTN;
    private javax.swing.JButton CancelBtTN1;
    private javax.swing.JButton ExportBTN;
    private javax.swing.JTextField Id_S1;
    private javax.swing.JTextField Id_S2;
    private javax.swing.JTextField Prj;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTable Tableselec;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField name_S1;
    private javax.swing.JTextField name_S2;
    private javax.swing.JTextField session_S1;
    private javax.swing.JTextField session_S2;
    // End of variables declaration//GEN-END:variables
}
